apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: json-server-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: clawguard-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: json-server-ca-issuer
spec:
  ca:
    secretName: json-server-ca
