FROM alpine:3.20
RUN apk add --no-cache curl \
 && curl -LO "https://dl.k8s.io/release/$(curl -Ls https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" \
 && install kubectl /usr/local/bin/ \
 && rm kubectl
